export const actionButtons = [
  {
    title: "Track Workout",
    screen: "Demo",
    color: "#E5962D",
    icon: "fitness",
    vertical: true,
    requiresPro: false,
  },
  {
    title: "Browse Workouts",
    screen: "Demo",
    color: "#1982c4",
    icon: "library",
    vertical: true,
    requiresPro: false,
  },
  {
    title: "Connect With Friends",
    screen: "Demo",
    color: "#f44174",
    icon: "share-social",
    vertical: false,
    requiresPro: true,
  },
  {
    title: "Add an Exercise",
    screen: "Demo",
    color: "#8ac926",
    icon: "add-circle",
    vertical: false,
    requiresPro: false,
  },
  {
    title: "Create a Routine",
    screen: "Demo",
    color: "#c03221",
    icon: "md-time",
    vertical: false,
    requiresPro: true,
  },
  {
    title: "Join Challenges",
    screen: "Demo",
    color: "#23967f",
    icon: "trophy",
    vertical: false,
    requiresPro: true,
  },
];
